import polars as pl
from jinja2 import Template
from datetime import datetime

class ReportEngine:
    """Generates HTML reports with embedded charts and data."""
    
    TEMPLATE = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Excel Analysis Report - {{ filename }}</title>
        <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background-color: #f4f4f9; color: #333; }
            .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
            h2 { color: #34495e; margin-top: 30px; }
            .metrics { display: flex; gap: 20px; margin-bottom: 30px; }
            .metric-card { background: #ecf0f1; padding: 15px; border-radius: 5px; flex: 1; text-align: center; }
            .metric-value { font-size: 24px; font-weight: bold; color: #2980b9; }
            .metric-label { font-size: 14px; color: #7f8c8d; }
            .chart-container { margin-bottom: 40px; border: 1px solid #ddd; padding: 20px; border-radius: 5px; background: white; }
            .plotly-chart { width: 100%; height: 500px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px; }
            th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
            th { background-color: #3498db; color: white; }
            tr:nth-child(even) { background-color: #f9f9f9; }
            .footer { margin-top: 50px; text-align: center; color: #95a5a6; font-size: 12px; }
        </style>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    </head>
    <body>
        <div class="container">
            <h1>📊 Analysis Report</h1>
            <p><strong>File:</strong> {{ filename }}</p>
            <p><strong>Generated on:</strong> {{ timestamp }}</p>

            <!-- Metrics Section -->
            <div class="metrics">
                <div class="metric-card">
                    <div class="metric-value">{{ total_rows }}</div>
                    <div class="metric-label">Total Rows</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{{ filtered_rows }}</div>
                    <div class="metric-label">Filtered Rows</div>
                </div>
            </div>

            <!-- Custom Metrics Section -->
            {% if numeric_summaries %}
            <h2>🔢 Numeric Summaries</h2>
            <div class="metrics">
                {% for item in numeric_summaries %}
                <div class="metric-card">
                    <div class="metric-value">{{ "{:,.2f}".format(item.value) }}</div>
                    <div class="metric-label">Sum of {{ item.column }}</div>
                    <div style="font-size: 11px; color: #aaa;">Total: {{ "{:,.2f}".format(item.total) }}</div>
                </div>
                {% endfor %}
            </div>
            {% endif %}

            {% if category_counts %}
            <h2>🔠 Category Counts</h2>
            <div class="metrics">
                {% for item in category_counts %}
                <div class="metric-card">
                    <div class="metric-value">{{ item.count }}</div>
                    <div class="metric-label">{{ item.category }}</div>
                    <div style="font-size: 11px; color: #aaa;">in {{ item.column }}</div>
                </div>
                {% endfor %}
            </div>
            {% endif %}

            <!-- Charts Section -->
            <h2>📈 Visualizations</h2>
            {% for title, chart_html in charts.items() %}
            <div class="chart-container">
                <h3>{{ title }}</h3>
                <div class="plotly-chart">{{ chart_html|safe }}</div>
            </div>
            {% endfor %}

            <!-- Data Table Section -->
            <h2>📄 Data Preview (Top 50)</h2>
            <div style="overflow-x: auto;">
                {{ table_html|safe }}
            </div>

            <div class="footer">
                Generated by Excel Analysis Tool
            </div>
        </div>
    </body>
    </html>
    """

    def generate_report(self, df, filename, figures, metrics):
        """
        Generates a complete HTML report string.
        df: Filtered Polars DataFrame
        filename: Name of the source file
        figures: Dictionary of Plotly figures {title: fig}
        metrics: Dictionary containing numeric summaries and category counts
        """
        # Convert figures to HTML div strings
        charts_html = {}
        for title, fig in figures.items():
            # include_plotlyjs=False because we included it in the head manually
            charts_html[title] = fig.to_html(full_html=False, include_plotlyjs=False)

        # Convert dataframe head to HTML table (Top 10 only)
        table_html = df.head(10).to_pandas().to_html(index=False, border=0, classes="dataframe")
        
        # Render template
        template = Template(self.TEMPLATE)
        html_out = template.render(
            filename=filename,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            total_rows=metrics["total_rows"], 
            filtered_rows=metrics["filtered_rows"],
            numeric_summaries=metrics["numeric_summaries"],
            category_counts=metrics["category_counts"],
            charts=charts_html,
            table_html=table_html
        )
        
        return html_out
